services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: steam
      POSTGRES_PASSWORD: steam
      POSTGRES_DB: steam
    ports:
      - "5432:5432"

  steam-inventory-tracker:
    image: jhrtmnn/steam-inventory-tracker:local
    container_name: steam-inventory-tracker
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/steam"
      SPRING_DATASOURCE_USERNAME: "steam"
      SPRING_DATASOURCE_PASSWORD: "steam"
    depends_on:
      - postgres