version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      ME_CONFIG_MONGODB_SERVER: mongodb

#  steam-inventory-tracker:
#    image: jhrtmnn/steam-inventory-tracker:main
#    container_name: steam-inventory-tracker
#    restart: unless-stopped
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATA_MONGODB_HOST: "mongodb"
#    depends_on:
#      mongo:
#        condition: service_healthy
#
#  frontend:
#    image: jhrtmnn/steam-inventory-tracker-frontend
#    container_name: steam-inventory-tracker-frontend
#    restart: unless-stopped
#    ports:
#      - "80:80"
#    depends_on:
#      steam-inventory-tracker:
#        condition: service_healthy