apiVersion: v1
kind: Secret
metadata:
  name: {{ include "steam-inventory-tracker.db.secretName" . }}
  labels:
    {{- include "steam-inventory-tracker.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.sit.datasource.password | default (randAlphaNum 10) | b64enc | quote }}