apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "steam-inventory-tracker.fullname" . }}
  labels:
    {{- include "steam-inventory-tracker.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "steam-inventory-tracker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "steam-inventory-tracker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "steam-inventory-tracker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: actuator
              containerPort: {{ .Values.service.actuatorPort }}
              protocol: TCP
          env:
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "steam-inventory-tracker.mongodb.secretName" . }}
                  key: mongodb-root-password
            - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
              value: {{ .Values.sit.mongodb.authenticationdatabase | quote }}
            - name: SPRING_DATA_MONGODB_USERNAME
              value: {{ .Values.mongodb.auth.rootUser | quote }}
            - name: SPRING_DATA_MONGODB_DATABASE
              value: {{ .Values.sit.mongodb.database | quote }}
            - name: SPRING_DATA_MONGODB_PORT
              value: {{ .Values.sit.mongodb.port | quote }}
            - name: SPRING_DATA_MONGODB_HOST
              value: {{ tpl .Values.sit.mongodb.host . | quote }}
            - name: SPRING_DATA_MONGODB_AUTO_INDEX_CREATION
              value: {{ .Values.sit.mongodb.autoindexcreation | quote }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: actuator
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: actuator
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}