apiVersion: v1
kind: Secret
metadata:
  name: {{ include "steam-inventory-tracker.mongodb.secretName" . }}
  labels:
    {{- include "steam-inventory-tracker.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-uri: {{ (required .Values.sit.mongodb.uri "Required property mongodb.uri missing" ) | b64enc | quote }}