apiVersion: v1
kind: Secret
metadata:
  name: {{ include "steam-inventory-tracker.fullname" . }}-mongodb-secret
  labels:
    {{- include "steam-inventory-tracker.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
type: Opaque
data:
  mongodb-root-password: {{ (.Values.mongodb.auth.rootPassword | default (randAlphaNum 32)) | b64enc | quote }}