apiVersion: v1
kind: Service
metadata:
  name: {{ include "steam-inventory-tracker.fullname" . }}
  labels:
    {{- include "steam-inventory-tracker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.actuatorPort }}
      targetPort: actuator
      protocol: TCP
      name: actuator
  selector:
    {{- include "steam-inventory-tracker.selectorLabels" . | nindent 4 }}
