steam:
  baseurl: "https://steamcommunity.com/market/priceoverview/?"
  path: "appid=730&currency=3&market_hash_name="
  timeoutDuration: PT10S # the default wait for permission duration
  limitRefreshPeriod: PT30S # wait time between periods
  limitForPeriod: 1 # apply the wait duration for every request
  sleep-duration: 30 # sleep duration between requests in seconds. Only relevant for the HttpClient
  # Retry configuration
  max-retry-attempts: 3 # maximum number of retry attempts
  retry-initial-backoff: PT1S # initial backoff duration
  retry-max-backoff: PT10S # maximum backoff duration
  retry-jitter: 0.5 # jitter factor for randomizing backoff
scheduler:
  #        ┌───────────── second (0-59)
  #        │ ┌───────────── minute (0 - 59)
  #        │ │  ┌───────────── hour (0 - 23)
  #        │ │  │  ┌───────────── day of the month (1 - 31)
  #        │ │  │  │ ┌───────────── month (1 - 12) (or JAN-DEC)
  #        │ │  │  │ │ ┌───────────── day of the week (0 - 7)
  #        │ │  │  │ │ │          (or MON-SUN -- 0 or 7 is Sunday)
  #        │ │  │  │ │ │
  request: 0 0 */3 * * * # every 3 hours
spring:
  application:
    name: steam-inventory-tracker
  data:
    mongodb:
      database: steam-inventory-tracker
      auto-index-creation: true
      uri: mongodb://localhost/test

management: # Spring management API config, see https://spring.io/guides/gs/centralized-configuration/
  endpoints:
    web:
      exposure:
        include: health, threaddump, loggers, prometheus, info, metrics
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: ping, mongo
        liveness:
          include: ping
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http: true
    tags:
      application: ${spring.application.name}
  server:
    port: 4004
