steam:
  baseurl: "https://steamcommunity.com/market/priceoverview/?"
  path: "appid=730&currency=3&market_hash_name="
  timeoutDuration: PT30M #
  limitRefreshPeriod: PT30S # wait time between periods
  limitForPeriod: 1 # apply the wait duration for every request
  sleep-duration: 15 # sleep duration between requests in seconds. Only relevant for the HttpClient
scheduler:
  #        ┌───────────── second (0-59)
  #        │ ┌───────────── minute (0 - 59)
  #        │ │  ┌───────────── hour (0 - 23)
  #        │ │  │  ┌───────────── day of the month (1 - 31)
  #        │ │  │  │ ┌───────────── month (1 - 12) (or JAN-DEC)
  #        │ │  │  │ │ ┌───────────── day of the week (0 - 7)
  #        │ │  │  │ │ │          (or MON-SUN -- 0 or 7 is Sunday)
  #        │ │  │  │ │ │
  request: 0 0 */3 * * * # every 3 hours
spring:
  application:
    name: steam-inventory-tracker
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: steam-inventory-tracker
      port: 27017
      host: localhost
      auto-index-creation: true

management: # Spring management API config, see https://spring.io/guides/gs/centralized-configuration/
  endpoints:
    web:
      exposure:
        include: health, threaddump, loggers, prometheus, info, metrics
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState, diskSpace
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http: true
    tags:
      application: ${spring.application.name}
  server:
    port: 4004
