steam:
  baseurl: "https://steamcommunity.com/market/priceoverview/?"
  path: "appid=730&currency=3&market_hash_name="
spring:
  application:
    name: steam-inventory-tracker
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: steam-inventory-tracker
      port: 27017
      host: localhost
      auto-index-creation: true

management: # Spring management API config, see https://spring.io/guides/gs/centralized-configuration/
  endpoints:
    web:
      exposure:
        include: health, threaddump, loggers, prometheus, info, metrics
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState, diskSpace
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http: true
    tags:
      application: ${spring.application.name}
  server:
    port: 4004
