scheduler:
  #        ┌───────────── second (0-59)
  #        │ ┌───────────── minute (0 - 59)
  #        │ │ ┌───────────── hour (0 - 23)
  #        │ │ │ ┌───────────── day of the month (1 - 31)
  #        │ │ │ │ ┌───────────── month (1 - 12) (or JAN-DEC)
  #        │ │ │ │ │ ┌───────────── day of the week (0 - 7)
  #        │ │ │ │ │ │          (or MON-SUN -- 0 or 7 is Sunday)
  #        │ │ │ │ │ │
  request: 0 0 0 1 1 * # At 00:00 on the 1st of January

spring:
  data:
    mongodb:
      host: rhea.local
