name: Release Helm Charts

on:
  workflow_dispatch: # Trigger manually
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  get-helm-charts-versions:
    outputs:
      latest_version: ${{ steps.step1.outputs.latest_version }}
      current_version: ${{ steps.step2.outputs.current_version }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get helm charts latest tag version
        id: step1
        run: |
          latestVersion=$(git tag | grep "steam-inventory-tracker-[1-9]" | tail -1)
          echo "::set-output name=latest_version::$latestVersion"
          echo "Exported $latestVersion latest helm charts version"
      - name: Get helm charts current version
        id: step2
        run: |
          chartVersion=steam-inventory-tracker-$(cat ./charts/steam-inventory-tracker/Chart.yaml | grep "version:" | head -1 | cut -d ":" -d " " -f2)
          echo "::set-output name=current_version::$chartVersion"
          echo "Exported $chartVersion helm charts version"


  release:
    needs: "get-helm-charts-versions"
    if: needs.get-helm-charts-versions.outputs.latest_version != needs.get-helm-charts-versions.outputs.current_version
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.8.1

      - name: Update helm dependencies
        run: |
          cd charts/steam-inventory-tracker
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm dependency update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
