name: Build, Test and Push

on:
  push:
    branches: [ main ]
    tags: [ '**' ]
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

env:
  TARGET_PLATFORMS: linux/amd64,linux/arm64
  IMAGE_NAMESPACE: jhrtmnn
  IMAGE_NAME: steam-inventory-tracker
jobs:
  build:
    name: Build and Test
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ds-jhartmann_steam-inventory-tracker

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.23.0
        if: always()
        with:
          files: |
            target/surefire-reports/*.xml

      # Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@b275d12641ac2d2108b2cbb7598b154ad2f2cee8 # 5.0.0

  push_to_registry:
    name: Push Docker image to Docker Hub
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.TARGET_PLATFORMS }}

      # https://github.com/peter-evans/dockerhub-description
      - name: Update Docker Hub description
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          IMAGE_NAMESPACE: ${{ env.IMAGE_NAMESPACE }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: ${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}
